### ISSUE TITLE
If I save the settings in the free version I get Warning:  Illegal string offset 'tab_activity_disabled'

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#105]
Warning:  Illegal string offset 'tab_activity_disabled' in  /Users/svenl77/Sites/buddyforms/wp-content/plugins/wc4bp/admin/admin.php  on line 127
--

![screenshot-buddyforms-2017-08-31-12-58-57](https://user-images.githubusercontent.com/645567/29920146-6ff59154-8e4c-11e7-9b97-ed00eae11840.png)

**Comment by marin250189** [comment]
Solved

**Comment by marin250189** [comment]
Solved
