### ISSUE TITLE
 Turn off 'Shop' Tab inside "Settings" for the activity stream settings.

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#106]
Tested with a fresh install of WordPress.

Why is the option checked ? 

![screenshot-ac231f3a-331c-d548-8043-03291f18da07-2017-08-31-13-05-58](https://user-images.githubusercontent.com/645567/29920319-47d74d10-8e4d-11e7-8f2a-28396cc97d82.png)

**Comment by marin250189** [comment]
Solved
