### ISSUE TITLE
Plugin not working after Installation on fresh WordPress in free version 

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#107]
![screenshot-ac231f3a-331c-d548-8043-03291f18da07-2017-08-31-13-10-15](https://user-images.githubusercontent.com/645567/29920456-d8093fec-8e4d-11e7-91ff-020ec5be0bad.png)

**Comment by svenl77** [comment]
The Shop is missing in menu and profile

**Comment by marin250189** [comment]
Solved
