### ISSUE TITLE
Turn off 'Shop' Tab inside "Settings" for the activity stream settings.

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#108]
The option enables and disables the complete plugin. I have tested it and it removes the shop tab and all sub tabs.

If I uncheck the setting and save all works again.
![screenshot-ac231f3a-331c-d548-8043-03291f18da07-2017-08-31-13-15-05](https://user-images.githubusercontent.com/645567/29920732-148234aa-8e4f-11e7-964e-81ecf48607ab.png)

This option was created to enable or disable the shop tab inside the settings tab.

Please see the screenshot of the  Shop Tab under Settings. This is the place where the options was created for

![screenshot-ac231f3a-331c-d548-8043-03291f18da07-2017-08-31-13-17-52](https://user-images.githubusercontent.com/645567/29920708-ee0428c4-8e4e-11e7-85d9-a111b7e2aee9.png)

**Comment by marin250189** [comment]
Solved
