### ISSUE TITLE
Duplicate Save Settings Button 

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#109]
Please see the screenshot 
![screenshot-ac231f3a-331c-d548-8043-03291f18da07-2017-08-31-13-17-52](https://user-images.githubusercontent.com/645567/29920788-718db5fc-8e4f-11e7-9fcd-334a339e1ea8.png)

**Comment by marin250189** [comment]
![image](https://user-images.githubusercontent.com/11038384/29953298-f58f927e-8e9c-11e7-850c-42c5425928f4.png)
Solved
