### ISSUE TITLE
HTTP Response 404 when click on BP purchased activity with WC 3+

### ISSUE THREAD

**Issue by denisleclerc** [Themekraft/wc4bp#163]
With wc4bp-premium WC4BP:	3.0.15, BuddyPress:	2.9.1, Woocommerce:	3.2.1
HTTP response is 404 when click on BP Purchased activity

Following modification fixes the bug:
in file : \WWW\wp-content\plugins\wc4bp-premium\class\core\wc4bp-helpers.php, line 214

**-  line causing the bug:**
`$names[] = '<a href="' . get_permalink( $product['item_meta']['_product_id'][0] ) . '">' .$product['name'] . '</a>';`
			

**- replaced by this line fixes the bug**
`$names[] = '<a href="' . $product->get_product()->get_permalink() . '">' . $product->get_product()->get_name() . '</a>';`

Denis

**Comment by gfirem** [comment]
@denisleclerc Thanks, i will test your solution and release a fix. I not understand where you face the issue, `click on BP Purchased activity` can you share an screenshoot with me or and example of the url. I want to go more deep in this issue

**Comment by denisleclerc** [comment]
Hello,
In BP of a user profile, you have an activity item when the user has an
order complete. A new activity line is displayed with link to the purchased
products...
[image: Images intégrées 1]

2017-12-18 23:24 GMT+01:00 Guillermo Figueroa Mesa <notifications@github.com

**Comment by gfirem** [comment]
@denisleclerc the image is not working.

**Comment by denisleclerc** [comment]
image with jpeg format and as attached not in the mail body

2017-12-19 0:24 GMT+01:00 Guillermo Figueroa Mesa <notifications@github.com>
:

**Comment by gfirem** [comment]
Sorry the image is not in the attachment. Don't worry, i get the idea with your explanation.
