### ISSUE TITLE
WCBP redirect cause infinite loop in URL of WooCommerce checkout page

### ISSUE THREAD

**Issue by denisleclerc** [Themekraft/wc4bp#164]
**HTTP request of WC checkout page leads to INET_E_REDIRECT_FAILED with WC4BP plugin activated**
I used : WP 4.8.4; WC 3.2.1; BP 2.9.1; WC4BP-premium 3.0.15

I fixed the bug by commenting the line 117 in file : WWW\wp-content\plugins\wc4bp-premium\class\core\wc4bp-redirect.php

```
if ( $payment_created_account === $checkout_page->post_name ) {
	//lenuage: commented next line fixe the bug NET_E_REDIRECT_FAILED 
	//return $url;
	}
```
It solved my problem but could you doubled check, explain to me the reason why you coded this `if `condition
and mention please  any risk for me having commented the `return $url` line

Thank you

**Comment by gfirem** [comment]
Hi @denisleclerc we remove that code in the last version we release today, was an old code to ensure the thank you page from woocommerce will be see it. Is not needed now. Please update and i thank you your help a lot. Please let me know at any time if we can help you again. Cheers.

**Comment by denisleclerc** [comment]
Hello,
For my use case, I need to  localize your plugin in fr_FR. I could send the
.po if you need
Sincerely
Denis Leclerc

2017-12-21 13:22 GMT+01:00 Guillermo Figueroa Mesa <notifications@github.com

**Comment by marin250189** [comment]
Hi @denisleclerc ,you can send us the .po file, thanks in advance.

**Comment by denisleclerc** [comment]
Hi,  the fr_FR .po file derived from the ones in  www\wp-content\plugins\wc4bp-premium\languages\ is available. I send it by email since .po format is not supported in the Github issues tracking messages
Denis

**Comment by denisleclerc** [comment]
Hi, Here, enclosed,  it is the fr_FR .po file for
www\wp-content\plugins\wc4bp-premium\languages\
Please confirm good receipt
Denis

2017-12-23 3:10 GMT+01:00 marin250189 <notifications@github.com>:

**Comment by denisleclerc** [comment]
here enclosed the .po file renamed .po.txt for github upload file compatibility
[wc4bp-fr_FR.po.txt](https://github.com/Themekraft/wc4bp/files/1604384/wc4bp-fr_FR.po.txt)

**Comment by gfirem** [comment]
@denisleclerc thanks for the traduction.
