### ISSUE TITLE
Too few argument counts - Woocommerce Version 3.4.6 Buddypress 3.2.0

### ISSUE THREAD

**Issue by pbradl42** [Themekraft/wc4bp#216]
I've just finished moving my site to a new server, so I'm not sure if this is because of an updated woocommerce or a misconfiguration on my end, but it looks like something was changed. This occurs at checkout -- the page itself just gives a 'server misconfigured error'. I replaced the path 'DIR'. Thanks!

2018-10-14T18:40:21+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function wc4bp_Woocommerce::avoid_override_of_user_meta(), 1 passed in DIR/wp-includes/class-wp-hook.php on line 288 and exactly 2 expected in DIR/wp-content/plugins/wc4bp-premium/class/wc4bp-woocommerce.php:47
Stack trace:
#0 DIR/wp-includes/class-wp-hook.php(288): wc4bp_Woocommerce->avoid_override_of_user_meta(Object(WC_Customer))
#1 DIR/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 DIR/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 DIR/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(956): do_action('woocommerce_che...', Object(WC_Customer), Array)
#4 DIR/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1029): WC_Checkout->process_customer(Array)
#5 DIR/wp-content/plugins/woocommerc

**Comment by gfirem** [comment]
Hi @pbradl42, sorry you are running into this issue. I was trying to replicate it, but this issue is not happening in my local environment. Would you like to reach me through the support and we can figure out what plugin is causing this issue.

**Comment by pbradl42** [comment]
OK, will do.
Thanks,
Peter
