### ISSUE TITLE
The tabs are returning 404

### ISSUE THREAD

**Issue by gfirem** [Themekraft/wc4bp#246]
**Description**
When you try to access to Download or Order tab they return 404.

**Steps to reproduce**
- Go to the BuddyPress user profile in the fronted
- Go to the sop tab
- Go to Order tab

**Expected behavior**
The plugin needs to show the corresponding tab with the original content from Woocommerce

**Support**
https://secure.helpscout.net/conversation/835622410/25098/
https://secure.helpscout.net/conversation/838069919/25124/

**Comment by alybarreno** [comment]
The behavior has been the expected

![image](https://user-images.githubusercontent.com/21145469/57327527-cc088980-70d4-11e9-9741-527dc42b6870.png)

![image](https://user-images.githubusercontent.com/21145469/57327534-d2970100-70d4-11e9-98dc-414e1e0c65dc.png)
