### ISSUE TITLE
Error on the style of Payment Tab

### ISSUE THREAD

**Issue by gfirem** [Themekraft/wc4bp#247]
**Description**
The Payment tab is not loading the stripe assets and it looks ugly, also don't work.

**Step to reproduce**
- Go to the BuddyPress user Profile
- Go to the Shop tab
- Go to the Payment tab
- Go to add a new Payment method

**Expected Behavior**
Show the stripe option inside the payment tab in the correct way, like do the same Woocomerce payment tab. 

**ScreenShoot**
![image](https://user-images.githubusercontent.com/11023116/57197443-b319a000-6f3d-11e9-888b-8a59d5bfb165.png)

**Support**
https://secure.helpscout.net/conversation/823654088/24965/

**Comment by alybarreno** [comment]
By clicking on the "Add payment method" button, the images of the large card types are displayed and the option of "use a new payment method" is not shown.

![image](https://user-images.githubusercontent.com/21145469/57327316-4389e900-70d4-11e9-871b-0464016ef74a.png)

**Comment by alybarreno** [comment]
The behavior has been the expected
