### ISSUE TITLE
Add Payment Option is not Working

### ISSUE THREAD

**Issue by gfirem** [Themekraft/wc4bp#250]
**Describe the bug**
If I try to add a new Payment option form the BuddyPress Profile is not working

**To Reproduce**
1. Go to the BuddyPress Profile Area in the frontend
2. Click on Shop tab
3. Click on the Payment Method tab
4. Click on the Add payment method button

**Expected behavior**
- After click on the Add payment button, it supposes to show a new form where you can add a new payment.
- After add a new payment method they need to redirect to the Payment Method tab
- The new payment method need to appear in the list of existing Payment Methods

**Screenshots**

![image](https://user-images.githubusercontent.com/11023116/57197992-1c041680-6f44-11e9-9421-ecb503ccb7ac.png)

**Context**
We are using the Stripe plugin for Woocommerce.
Read more in https://docs.woocommerce.com/document/stripe/

**Comment by alybarreno** [comment]
Clicking the "Add payment method" button displays the images of the different types of large cards

![image](https://user-images.githubusercontent.com/21145469/57326797-e3df0e00-70d2-11e9-8f9d-ce0425017cd2.png)

![image](https://user-images.githubusercontent.com/21145469/57326808-efcad000-70d2-11e9-8471-0e1936af0042.png)

**Comment by alybarreno** [comment]
The behavior has been the expected
