### ISSUE TITLE
Edit Billing Address is not working

### ISSUE THREAD

**Issue by gfirem** [Themekraft/wc4bp#252]
**Describe the bug**
Is not possible to Edit the Billing Address from the Address tab.

**To Reproduce**
1. Go to the BuddyPress Profile Area in the frontend 
2. Click on Shop tab
3. Click on the Address tab
4. Click on the Edit link in the Billing Address Section

**Expected behavior**
- When the user clicks on the edit link the form to edit the Billing Address need to appear
- On submitting the form to edit the Billing Adress it needs to redirect to the Address tab
- The Billing Address needs to be updated on form submit

**Screenshots**
![image](https://user-images.githubusercontent.com/11023116/57197643-4bb11f80-6f40-11e9-999c-9ab9622a865e.png)

**Comment by alybarreno** [comment]
The behavior has been correct
