### ISSUE TITLE
Edit Shipping Address is not working

### ISSUE THREAD

**Issue by gfirem** [Themekraft/wc4bp#253]
**Describe the bug**
Is not possible to Edit the Shipping Address from the Address tab.

**To Reproduce**
1. Go to the BuddyPress Profile Area in the frontend 
2. Click on Shop tab
3. Click on the Address tab
4. Click on the Edit link in the Shipping Address Section

**Expected behavior**
- When the user clicks on the edit link the form to edit the Shipping address need to appear
- On submitting the form to edit the Shipping Adress it needs to redirect to the Address tab
- The Shipping Address needs to be updated on form submit

**Screenshots**
![image](https://user-images.githubusercontent.com/11023116/57197587-9da57580-6f3f-11e9-9529-15dc82b8ca73.png)

**Comment by alybarreno** [comment]
The behavior has been correct
