### ISSUE TITLE
Add a filter to change the wc4bp_ slug in the url

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#28]
no option needed. just a filter and we need to write some documentation

**Comment by gfirem** [comment]
Ready! This to work is necesary to disblad/enabled the plugins. To generate all pages with the new suffix, prefer in the next order, disable the plugins. implement the filter, enabled the plugins. 

![image](https://cloud.githubusercontent.com/assets/11023116/22785195/b857722a-eea9-11e6-9102-e6ea3bc4ec4d.png)

![image](https://cloud.githubusercontent.com/assets/11023116/22785200/bc38fdaa-eea9-11e6-9011-8a0ab2b86b94.png)
