### ISSUE TITLE
Merchant rating

### ISSUE THREAD

**Issue by fiz192** [Themekraft/wc4bp#36]
First of all, Love the integrations! Thank you for doing this :)

Anyways, I was messing around with your plugin integrations and notice that when I click rating reviews for each merchant, it does not redirect to the buddypress version.

Is this intentional?

**Comment by svenl77** [comment]
@fiz192 Thanks for reporting. I was not able to recreate the issue can you provide the correct steps? All review work for me and I not find one place where you can review in the profile. Or do you talk about WC BP Vendors? I need more details please.
