### ISSUE TITLE
restrict suffix title

### ISSUE THREAD

**Issue by gfirem** [Themekraft/wc4bp#37]
Applying the suffix title only in the page list into the admin

**Comment by svenl77** [comment]
Hi @gfirem I guess this one is fixed? How can I test it

**Comment by gfirem** [comment]
![image](https://cloud.githubusercontent.com/assets/11023116/23021816/39fddcd6-f424-11e6-8ce8-58cc1eae80e5.png)

The main issue was in the title of page it add the suffix in all place, i limit only to the edit page. In the image you can see fixed.
