### ISSUE TITLE
 Notice: Trying to get property of non-object in plugins/wc4bp/class/core/wc4bp-redirect.php on line 225

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#39]
Notice: Trying to get property of non-object in plugins/wc4bp/class/core/wc4bp-redirect.php on line 225

**Comment by gfirem** [comment]
This is related to the issue https://github.com/Themekraft/wc4bp/issues/41

**Comment by svenl77** [comment]
fixed
