### ISSUE TITLE
Add Dependancies check with TGM

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#6]
At the moment if WooCommerce is deactivated there are two admin notice 

WC BP Integration needs WooCommerce to be installed. Download it now!
WC BP Integration needs WooCommerce to be installed. Download it now!

Please let us change to TGM. We use it also in the BuddyForms Plugin and its really useful.  http://tgmpluginactivation.com/

**Comment by gfirem** [comment]
I dont follow this, you want to include this library to handle the requirements

**Comment by svenl77** [comment]
yes exactly use TGM to check against WooCommerce and BuddyPress. It enables us to manage the dependencies without much coding and keep it constant. Check the example https://gist.github.com/svenl77/c5c580d38e48a64c78b220f2a59244e0
