### ISSUE TITLE
Duplicate billing address 

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#64]
Feedback from support:

When I activated my licence and updated my sync settings, it recreated the xProfile groups, so now I have two different "Billing Address" and "Mailing Address groups in my BP fields (see attached screenshot). I don't know which ones are the ones that already have my user's historical data, so I'm afraid to delete either one. What should I do?

**Comment by AiratHalitov** [comment]
The same problem every time after install this plugin.
You can delete one of them which empty.

**Comment by gfirem** [comment]
I can't replicate this, i need more info.

**Comment by haiderkb** [comment]
Deleting duplicate addresses caused both sets to disappear on mine. I uninstalled and reinstalled plugin and no addresses appeared at all. even after sync.

Only way to repeat was to install plugin on fresh WP install. Repeat of above caused same problem.

**Comment by gfirem** [comment]
This is resolve for the next release.
