### ISSUE TITLE
Ask for review

### ISSUE THREAD

**Issue by svenl77** [Themekraft/wc4bp#86]
We need a system to ask for reviews. We have only 3 reviews and 1 is a 1 star review. I have added ask for reviews into BuddyForms and collected 20 5 star in a short time frame.

**Comment by gfirem** [comment]
Interesting, i like the idea. I will run into this.

**Comment by svenl77** [comment]
@gfirem please read this and let us do something. we need review!! https://freemius.com/blog/how-we-increase-our-wordpress-plugin-reviews-by-700-percent/

**Comment by gfirem** [comment]
This need a better text.
